set(CMAKE_ASM_NASM_COMPILE_OBJECT
        "<CMAKE_ASM_NASM_COMPILER> <FLAGS> -f elf64 <INCLUDES> -o <OBJECT> <SOURCE>"
)
set(CMAKE_C_COMPILE_OBJECT
        "<CMAKE_C_COMPILER> <FLAGS> -target x86_64-pc-none-elf  <INCLUDES> -c -o <OBJECT> <SOURCE>"
)
set(CMAKE_CXX_COMPILE_OBJECT
        "<CMAKE_CXX_COMPILER> <FLAGS> -target x86_64-pc-none-elf <INCLUDES> -c -o <OBJECT> <SOURCE>"
)

set(CMAKE_C_LINK_EXECUTABLE
        "<CMAKE_LINKER> -flavor gnu <LINK_FLAGS> -entry:_start -nodefaultlib --gc-sections  ${SHIRO_CXX_PREOBJECTS_ELF} <OBJECTS> <LINK_LIBRARIES> ${SHIRO_CXX_POSTOBJECTS_ELF} -o <TARGET>"
)

set(CMAKE_CXX_LINK_EXECUTABLE
        "<CMAKE_LINKER> -flavor gnu <LINK_FLAGS> -entry:_start -nodefaultlib --gc-sections  ${SHIRO_CXX_PREOBJECTS_ELF} <OBJECTS> <LINK_LIBRARIES> ${SHIRO_CXX_POSTOBJECTS_ELF} -o <TARGET>"
)

set(CMAKE_ASM_NASM_LINK_EXECUTABLE
        "<CMAKE_LINKER> -flavor gnu <LINK_FLAGS> -entry:_start -nodefaultlib --gc-sections  ${SHIRO_CXX_PREOBJECTS_ELF} <OBJECTS> <LINK_LIBRARIES> ${SHIRO_CXX_POSTOBJECTS_ELF} -o <TARGET>"
        y)

set(TARGET_OBJECT "ELF" CACHE INTERNAL "Target object format" FORCE)
set(CMAKE_EXECUTABLE_SUFFIX "")